version: "2"

services:

  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    extends: 
      file: common-services.yml
      service: elasticsearch
    ports:
    - 9200:9200     # elasticsearch
    - 9300:9300     # elasticsearch
    

  logstash:
    build: logstash
    extends: 
      file: common-services.yml
      service: logstash
    # volumes: 
    # - ./logstash/pipeline:/usr/share/logstash/pipeline

  kibana:
    build: kibana
    extends: 
      file: common-services.yml
      service: kibana

  nginx:
    build: nginx
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - kibana
    - elasticsearch
    - logstash
    ports:
    - 5601:5601     # kibana
    - 5000:5000     # logstash syslog/tcp
    - 5000:5000/udp # logstash syslog/udp
    - 5043:5043     # logstash beats

volumes:
  esdata: