version: "2"

services:
  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch:0.1-xpack
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - ${ES_DATA_HOME}:/usr/share/elasticsearch/data

  logstash:
    image: ${REGISTRY_URL}/logstash:0.1-xpack
    extends: 
      file: common-services.yml
      service: logstash

  kibana:
    image: ${REGISTRY_URL}/kibana:0.1-xpack
    extends: 
      file: common-services.yml
      service: kibana

  nginx:
    image: ${REGISTRY_URL}/nginx-elk
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - kibana
    - elasticsearch
    - logstash
    ports:
    - 5601:5601     # kibana
    - 9200:9200     # elasticsearch
    - 5000:5000     # logstash syslog/tcp
    - 5000:5000/udp # logstash syslog/udp
    - 5043:5043     # logstash beats

#   headplug:
#     extends: 
#       file: common-services.yml
#       service: headplug
#     ports:
#     - 9100:9100

volumes:
  esdata: