version: "2"

services:
  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata:/opt/elasticsearch/data
    extends: 
      file: common-services.yml
      service: elasticsearch
    environment: 
      - ES_JAVA_OPTS=-Xmx512m -Xms512m

  logstash:
    build: logstash
    extends: 
      file: common-services.yml
      service: logstash
    environment: 
      - LS_JAVA_OPTS=-Xmx512m -Xms512m

  kibana:
    build: kibana
    extends: 
      file: common-services.yml
      service: kibana

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    network_mode: "service:logstash"
    depends_on: 
    - logstash

  nginx:
    build: nginx
    extends: 
      file: common-services.yml
      service: nginx

  filebeat:
    build: filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    volumes: 
      - fbdata:/data

  headplug:
    extends: 
      file: common-services.yml
      service: headplug

  cadvisor:
    extends: 
      file: common-services.yml
      service: cadvisor

volumes:
  esdata:
  fbdata: