version: "2"

services:

  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch:${IMAGE_TAG}
    extends: 
      file: common-services.yml
      service: elasticsearch
    environment:
    - "discovery.zen.ping.unicast.hosts=${ES_MASTER_NODE_HOST}"
    - "discovery.zen.minimum_master_nodes=${ES_MINIMUM_MASTER_NODE}"
    - "transport.publish_port=9301"
    restart: "unless-stopped"

  nginx:
    image: ${REGISTRY_URL}/nginx-elk:0.1
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - elasticsearch
    extra_hosts:
    - kibana:127.0.0.1
    - logstash:127.0.0.1
    ports:
    #- 9200:9200     # elasticsearch
    - 9301:9300     # elasticsearch
    restart: "unless-stopped"

volumes:
  esdata:
  esbackup: