version: "2"

services:

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    depends_on: 
    - logstash
    extra_hosts: 
    - "logstash:${LOGSTASH_HOST}"
    command: syslog://${LOGSTASH_HOST}:5000
    #network_mode: "service:logstash"

  filebeat:
    build: filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    volumes: 
      - fbdata:/data
    extra_hosts: 
    - "logstash:${LOGSTASH_HOST}"

volumes:
  fbdata: