version: "2"

services:

  elasticsearch:
    build: elasticsearch
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    - ${ES_BACKUP_HOME}:/usr/share/elasticsearch/backups

  logstash:
    build: logstash
    extends: 
      file: common-services.yml
      service: logstash

  kibana:
    build: kibana
    extends: 
      file: common-services.yml
      service: kibana

  nginx:
    build: nginx
    extends: 
      file: common-services.yml
      service: nginx
    ports:
    - 5601:5601     # kibana
    depends_on: 
    - kibana
    - elasticsearch
    - logstash

volumes:
  esdata:
  esbackup: