version: "3"

services:

  elasticsearch1:
    build: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    - esbackup:/usr/share/elasticsearch/backups
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
    - "discovery.zen.ping.unicast.hosts=127.0.0.1"
    - "discovery.zen.minimum_master_nodes=2"
    - ES_JAVA_OPTS
    ports:
    - 9200     # elasticsearch
    - 9300     # elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"

  elasticsearch2:
    build: elasticsearch
    volumes:
    - esdata2:/usr/share/elasticsearch/data
    - esbackup:/usr/share/elasticsearch/backups
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
    - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    - "discovery.zen.minimum_master_nodes=2"
    - ES_JAVA_OPTS
    ports:
    - 9200     # elasticsearch
    - 9300     # elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"

volumes:
  esdata:
  esdata2:
  esbackup: