version: "2"

services:

  nginx:
    ports:
    - 5601:5601     # kibana
    - 9200:9200     # elasticsearch
    - 9300:9300     # elasticsearch
    - 5000:5000     # logstash syslog/tcp
    - 5000:5000/udp # logstash syslog/udp
    - 5043:5043     # logstash beats
    volumes:
    - $PWD/ssl/es-cert.pem:/etc/nginx/ssl/nginx.crt
    - $PWD/ssl/es-key.pem:/etc/nginx/ssl/nginx.key
    - $PWD/ssl/ca.pem:/etc/nginx/ssl/ca.crt