version: "2"

services:
  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch
    volumes:
    - esdata:/opt/elasticsearch/data
    extends: 
      file: common-services.yml
      service: elasticsearch

  logstash:
    image: ${REGISTRY_URL}/logstash
    extends: 
      file: common-services.yml
      service: logstash
    ports:
    - 127.0.0.1:5043:5043

  kibana:
    image: ${REGISTRY_URL}/kibana
    extends: 
      file: common-services.yml
      service: kibana

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    depends_on: 
    - logstash
    #network_mode: "service:logstash"

  nginx:
    image: ${REGISTRY_URL}/nginx-elk
    extends: 
      file: common-services.yml
      service: nginx

  filebeat:
    image: ${REGISTRY_URL}/filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    volumes: 
    - fbdata:/data

  headplug:
    extends: 
      file: common-services.yml
      service: headplug

volumes:
  esdata:
  fbdata: