version: "2"

services: 
  curator:
    build: curator
    network_mode: "service:elasticsearch"
    volumes: 
    - ./curator/actions:/usr/share/curator
    environment:
    - SNAPSHOT_REPOSITORY=local
    - SNAPSHOT_INDEX_PREFIX
    - SNAPSHOT_INDEX_RETENTION_PERIOD
    - SNAPSHOT_RETENTION_PERIOD
    - SNAPSHOT_NAME_PREFIX
    depends_on: 
    - elasticsearch