version: "2"

services:

  elasticsearch:
    build: elasticsearch
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - ${ES_DATA_HOME}:/usr/share/elasticsearch/data
    - ${ES_BACKUP_HOME}:/usr/share/elasticsearch/backups
    - $PWD/ssl/ca.pem:/usr/share/elasticsearch/config/ssl/ca.crt
    - $PWD/ssl/es-cert.pem:/usr/share/elasticsearch/config/ssl/node1.crt
    - $PWD/ssl/es-key.pem:/usr/share/elasticsearch/config/ssl/node1.key

  logstash:
    build: logstash
    extends: 
      file: common-services.yml
      service: logstash

  kibana:
    build: kibana
    extends: 
      file: common-services.yml
      service: kibana

  nginx:
    build: nginx
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - kibana
    - elasticsearch
    - logstash
    ports:
    - 5601:5601     # kibana
    - 9200:9200     # elasticsearch
    - 9300:9300     # elasticsearch
    - 5000:5000     # logstash syslog/tcp
    - 5000:5000/udp # logstash syslog/udp
    - 5043:5043     # logstash beats
    volumes:
    - $PWD/ssl:/usr/share/nginx/conf.d/ssl

volumes:
  esdata:
  esbackup: