version: "2"

services:

  elasticsearch:
    volumes:
    - ${SSL_DIR}/ca.pem:/usr/share/elasticsearch/config/ssl/ca.crt
    - ${SSL_DIR}/server-cert.pem:/usr/share/elasticsearch/config/ssl/node1.crt
    - ${SSL_DIR}/server-key.pem:/usr/share/elasticsearch/config/ssl/node1.key

  nginx:
    ports:
    - 5601:5601     # kibana
    - 9200:9200     # elasticsearch
    - 9300:9300     # elasticsearch
    - 5000:5000     # logstash syslog/tcp
    - 5000:5000/udp # logstash syslog/udp
    - 5043:5043     # logstash beats
    volumes:
    - ${SSL_DIR}/server-cert.pem:/etc/nginx/ssl/nginx.crt
    - ${SSL_DIR}/server-key.pem:/etc/nginx/ssl/nginx.key
    - ${SSL_DIR}/ca.pem:/etc/nginx/ssl/ca.crt