version: "2"

services:
  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch
    volumes:
    - esdata:/opt/elasticsearch/data
    extends: 
      file: common-services.yml
      service: elasticsearch

  logstash:
    image: ${REGISTRY_URL}/logstash
    extends: 
      file: common-services.yml
      service: logstash
    ports:
    - 127.0.0.1:5043:5043

  kibana:
    image: ${REGISTRY_URL}/kibana
    extends: 
      file: common-services.yml
      service: kibana

  nginx:
    image: ${REGISTRY_URL}/nginx-elk
    extends: 
      file: common-services.yml
      service: nginx
    ports:
    - 5601:5601
    - 9200:9200

  headplug:
    extends: 
      file: common-services.yml
      service: headplug
    ports:
    - 9100:9100

volumes:
  esdata:
  fbdata: