version: "2"

services: 
  curator:
    build: curator
    network_mode: "service:elasticsearch"
    volumes: 
    - ./curator/actions:/usr/share/curator
    environment: 
    - CURATOR_HTTP_AUTH=${ES_USER}:${ES_PASSWORD}
    - CURATOR_USE_SSL=False
    - SNAPSHOT_REPOSITORY=local
    depends_on: 
    - elasticsearch