version: "2"

services: 
  curator:
    build: curator
    network_mode: "service:elasticsearch"
    volumes: 
    - ./curator/actions:/usr/share/curator
    environment: 
    - ES_HOST
    - ES_PORT
    - USE_SSL=False
    depends_on: 
    - elasticsearch