version: "2"

services:

  elasticsearch:
    build: elasticsearch
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    - ${ES_BACKUP_HOME}:/usr/share/elasticsearch/backups
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - $PWD/ssl/ca.pem:/usr/share/elasticsearch/config/ssl/ca.crt
    - $PWD/ssl/es-cert.pem:/usr/share/elasticsearch/config/ssl/node1.crt
    - $PWD/ssl/es-key.pem:/usr/share/elasticsearch/config/ssl/node1.key
    environment:
    - "discovery.zen.ping.unicast.hosts=${ES_MASTER_NODE_HOST}"
    - "discovery.zen.minimum_master_nodes=${ES_MINIMUM_MASTER_NODE}"
    - "transport.publish_port=9301"
    #ports:
    #- 9301:9300     # elasticsearch

  nginx:
    build: nginx
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - elasticsearch
    extra_hosts:
    - kibana:127.0.0.1
    - logstash:127.0.0.1
    ports:
    #- 9200:9200     # elasticsearch
    - 9301:9300     # elasticsearch
    volumes:
    - $PWD/ssl:/usr/share/nginx/conf.d/ssl

volumes:
  esdata:
  esbackup: