# https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

http.host: "0.0.0.0"

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: 'https://elasticsearch:9200'
#xpack.monitoring.elasticsearch.username: ${ES_USERNAME}
#xpack.monitoring.elasticsearch.password: ${ES_PASSWORD}

config.reload.automatic: true
#log.level: debug
